webapp/models/image.py
from .base import db


class Image(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    image_name = db.Column(db.String(30))
    image_path = db.Column(db.String(260), unique=True)
    image_tn_path = db.Column(db.String(260), unique=True)
    image_de_path = db.Column(db.String(260), unique=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', backref=db.backref('images', lazy=True))

    def __init__(self, image_name, image_path, image_tn_path, image_de_path, user_id):
        self.image_name = image_name
        self.image_path = image_path
        self.image_tn_path = image_tn_path
        self.image_de_path = image_de_path
        self.user_id = user_id

    def __repr__(self):
        return '<Image path %r>' % self.image_path

webapp/controllers/imageController.py
from flask_login import current_user, login_required
from flask import Blueprint, render_template, request, current_app, send_from_directory
from webapp.services import imageService
from PIL import Image
import io

imageManager = Blueprint("imageManager", __name__)

IMAGE_UPLOAD_PAGE = "imageUpload.html"
INTERNAL_ERROR_MSG = "Internal Error, please try again later."
IMAGE_NAME_LENGTH_ERROR = "Image name should be less than 30 characters, you can optional input an image alias instead."
IMAGE_SIZE_ERROR = "Image size exceeds maximum limit 2500*2500!"
IMAGE_TYPE_ERROR = "Invalid Image! Only JPEG, JPG, PNG files are accepted!"
UPLOAD_SUCCESS_MSG = "Image '{}' is uploaded successfully!"


@imageManager.route("/images", methods=["GET"])
@login_required
def get_images():
    username = current_user.username
    images = imageService.get_images_by_user()
    return render_template("images.html", title="Images", username=username, images=images,
                           s3Location=current_app.config["S3_BUCKET_LOCATION"])


@imageManager.route("/images/upload", methods=["GET", "POST"])
@login_required
def upload_image():
    upload_image_form = imageService.UploadImageForm()
    try:
        if upload_image_form.validate_on_submit():
            image = upload_image_form.image

            image_name = upload_image_form.imageName.data + "." + image.data.filename.split('.')[1] \
                if upload_image_form.imageName and len(upload_image_form.imageName.data.strip()) != 0 \
                else image.data.filename
            current_app.logger.info("----------Image name is {} ----------".format(image_name))
            if len(image_name) > 30:
                current_app.logger.error("----------400 {} ----------".format(IMAGE_NAME_LENGTH_ERROR))
                return render_template(IMAGE_UPLOAD_PAGE, form=upload_image_form, error=IMAGE_NAME_LENGTH_ERROR), 400

            blob = image.data.read()
            if request.cookies and "fileSize" in request.cookies:
                current_app.logger.debug("----------fileSize in cookie is found!----------")
                if not imageService.allowed_image_size(request.cookies["fileSize"]):
                    current_app.logger.error("----------400 {} ----------".format(IMAGE_SIZE_ERROR))
                    return render_template(IMAGE_UPLOAD_PAGE, form=upload_image_form, error=IMAGE_SIZE_ERROR), 400
            else:
                current_app.logger.info("----------fileSize in cookie is not found!----------")
                size = len(blob)
                if not imageService.allowed_image_size(size):
                    current_app.logger.error("----------400 {} ----------".format(IMAGE_SIZE_ERROR))
                    return render_template(IMAGE_UPLOAD_PAGE, form=upload_image_form, error=IMAGE_SIZE_ERROR), 400

            if imageService.image_validation(image_name):
                image_name_org = imageService.save_image(image_name, blob)
                current_app.logger.info("----------200 {} ----------".format(UPLOAD_SUCCESS_MSG.format(image_name_org)))
                return render_template(IMAGE_UPLOAD_PAGE, form=upload_image_form,
                                       message=UPLOAD_SUCCESS_MSG.format(image_name))
            else:
                current_app.logger.error("----------400 {} ----------".format(IMAGE_TYPE_ERROR))
                return render_template(IMAGE_UPLOAD_PAGE, form=upload_image_form, error=IMAGE_TYPE_ERROR), 400
        else:

            if request == 'POST':
                current_app.logger.error("----------Internal Error: {}----------".format(upload_image_form.errors))
                return render_template(IMAGE_UPLOAD_PAGE, form=upload_image_form, error=INTERNAL_ERROR_MSG), 500
        return render_template(IMAGE_UPLOAD_PAGE, form=upload_image_form)
    except Exception as e:
        current_app.logger.error("----------Internal Error: {}----------".format(str(e)))
        return render_template(IMAGE_UPLOAD_PAGE, form=upload_image_form, error=INTERNAL_ERROR_MSG), 500


@imageManager.route('/images/<path:filename>')
@login_required
def show_image(filename):
    image = imageService.get_images_by_filename(filename)
    return render_template("imageShow.html", image=image, s3Location=current_app.config["S3_BUCKET_LOCATION"])

webapp/controllers/userController.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_user, current_user, logout_user
from webapp.services import userService
from sqlalchemy.exc import IntegrityError
import os
from flask import current_app


users = Blueprint('users', __name__)

LOGIN_PAGE = "login.html"
REGISTER_PAGE = "register.html"
INTERNAL_ERROR_MSG = "Internal Error, please try again later."
AUTHENTICATION_ERROR = "Login Unsuccessful. Please check username and password."
REG_SUCCESS_MSG = "Registration successful, please login."
USER_EXISTED_ERROR = "User with username '{}' already exists."


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('imageManager.get_images'))
    form = userService.LoginForm()
    if form.validate_on_submit():
        authenticated_user = userService.is_authenticated(username=form.username.data, password=form.password.data)
        if authenticated_user:
            login_user(authenticated_user, remember=form.remember_user.data)
            next_page = request.args.get('next')
            current_app.logger.info("----------User '{}' login success !----------".format(authenticated_user.username))
            return redirect(next_page) if next_page else redirect(url_for('imageManager.get_images'))
        else:
            current_app.logger.error("----------User '{}' Login failed, username/password do not match record----------"
                                     .format(form.username.data))
            return render_template(LOGIN_PAGE, title='Login', form=form, error=AUTHENTICATION_ERROR), 401
    else:
        if request == 'POST':
            current_app.logger.error("----------Internal Error: {}----------".format(form.errors))
            return render_template(LOGIN_PAGE, title='Login', form=form, error=INTERNAL_ERROR_MSG), 500
    return render_template(LOGIN_PAGE, title='Login', form=form)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = userService.CreateUserForm()
    if current_user.is_authenticated:
        return redirect(url_for('imageManager.get_images'))
    if form.validate_on_submit():
        user_with_username = userService.get_user_by_username(username=form.username.data)

        if user_with_username:
            current_app.logger.error("----------409 Registration conflict: {} already exists----------"
                                     .format(form.username.data))
            return render_template(REGISTER_PAGE, title='Register', form=form,
                                   error=USER_EXISTED_ERROR.format(form.username.data)), 409
        else:
            try:
                user = userService.create_user(username=form.username.data, password=form.password.data)
                login_form = userService.LoginForm()
                current_app.logger.info("----------User '{}' register successful----------".format(user.username))
                return render_template(LOGIN_PAGE, title='Login', form=login_form, message=REG_SUCCESS_MSG)
            except IntegrityError as e:
                current_app.logger.error("----------Database action error: {}----------".format(str(e)))
                return render_template(REGISTER_PAGE, title='Register', form=form, error=INTERNAL_ERROR_MSG), 500
    else:
        if request.method == 'POST':
            current_app.logger.error("----------Internal Error: {}----------".format(form.errors))
            return render_template(REGISTER_PAGE, title='Register', form=form, error=INTERNAL_ERROR_MSG), 500
    return render_template(REGISTER_PAGE, title='Register', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

webapp/templates/imageShow.html
{% extends "layout.html" %}
{% block content %}
    <section>
        <div class="spacer-50"></div>
        <div class="container bg-white shadow rounded-lg">
            <div class="row align-center">
                <h3 class="mb-4" style="padding-top: 2rem">Raw Image: </h3>
            </div>

            <div class="row align-center" >
                <img style="max-width: 80%" src="{{s3Location}}{{image.image_path}}"/>
            </div>
            <div class="spacer-50"></div>
            <div class="row align-center">
                <h3 class="mb-4" style="padding-top: 2rem">After Text Detection: </h3>
            </div>
            <div class="row align-center" >
                <img style="max-width: 80%" src="{{s3Location}}{{image.image_de_path}}"/>
            </div>

          <div class="spacer-80"></div>
          <div class="row align-center" style="padding-bottom: 5rem">
              <a class="btn btn-lg btn-dark-blue" style="width: 50%" href="/images">
                <span class="button-text">Back to Image List</span>
                <span class="button-text-small">Back</span>
              </a>
          </div>
          <div class="spacer-80"></div>

        </div>

    </section>
{% endblock content %}

webapp/templates/imageUpload.html
{% extends "layout.html" %}
{% block content %}
  <section>
  <div class="container p-4">
    <div class="row mb-5 text-center text-white">
    </div>
    <div class="row">
      <div class="col-lg-6 mx-auto">
        <div class="p-5 bg-white shadow rounded-lg"><img src="../static/images/upload.png" alt="" width="200" class="d-block mx-auto mb-4">
          <h4 class="text-center mb-4 text-muted">
            Upload photos
          </h4>
          <div class="spacer-50"></div>
          <form action="/images/upload" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.imageName.label(class="form-control-label") }}
                {% if form.imageName.errors %}
                    {{ form.imageName(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.imageName.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    <input type="text" class="form-control" id="image-name" name="imageName"
                     placeholder="Optionally type in an image alias..."/>

                {% endif %}
            </div>

            <div class="form-group">
              <div class="custom-file rounded-pill mb-5">
                {% if form.image.errors %}
                    <input type="file" class="custom-file-input rounded-pill is-invalid" accept='image/*' name="image" id="image-file" oninput="fileSize();">
                    <label class="custom-file-label rounded-pill" for="image">Select image...</label>

                    <div class="invalid-feedback">
                        {% for error in form.image.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                  <input type="file" class="custom-file-input rounded-pill" accept='image/*' name="image" id="image-file" oninput="fileSize();">
                  <label class="custom-file-label rounded-pill" for="image">Select image...</label>
                {% endif %}
            </div>
          </div>
            <div class="form-group">
                  <button type="submit" name="submit" id="btnFetch" class="btn btn-lg btn-dark-blue" style="width:100%" >Upload</button>
                  <button  type="submit" name="submit" id="btnFetch1" class="btn btn-lg btn-dark-blue" style="width:100%" disabled hidden>
                    <span class="spinner-border" role="status" aria-hidden="true" style="margin-right: 10%"></span> Uploading...
                  </button>
            </div>
          </form>

          <h6 class="text-center mb-4 text-muted">
            * Only JPEG, JPG, PNG files are accepted.
          </h6>
          <div class="spacer-30"></div>
          <div class="row align-center">
              <a class="btn btn-lg btn-dark-blue" style="width: 50%" href="/images">
                  <span class="button-text">Back to Image List</span>
                  <span class="button-text-small">Back</span>
              </a>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

webapp/templates/images.html
{% extends "layout.html" %}
{% block content %}
    <div class="spacer-50"></div>
    <section>
        {% if images.count() > 0 %}
        <div class="container bg-white shadow rounded-lg" style="opacity: 0.92">
            <div class="row" style="padding-bottom: 3rem">
                <div class="col-lg-12">
                    <h1 class="mb-4" style="padding-top: 1.5rem; padding-left: 1rem">Hey {{ username }}, see images: </h1>
                    <hr>
                </div>
                {% for image in images %}
                <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                    <a class="align-center" style="height: auto;" href="{{ url_for('imageManager.show_image', filename=image.image_path.rsplit('/', 1)[-1]) }}">
                        <img class="img-thumbnail" src="{{s3Location}}{{image.image_tn_path}}"/>
                    </a>
                    <span class="align-center" style="height: auto;">{{ image.image_name }}</span>
                    <div class="spacer-30"></div>

                </div>
                {% endfor %}
            </div>
        </div>
        {% else %}
        <h1 class="mb-4">Welcome {{ username }} ! </h1>
        {% endif %}
    </section>
{% endblock content %}

webapp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/main.css') }}">

    {% if title %}
        <title>{{ title }}</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('imageManager.upload_image') }}" style="padding-right: 3rem">Upload Images</a>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% if error %}
            <div class="alert alert-warning alert-dismissible fade show">
                <strong style="margin-right: 2rem">Warning!</strong> {{ error }}
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            </div>
          {% endif %}

          {% if message %}
            <div class="alert alert-success alert-dismissible fade show">
                <strong style="margin-right: 2rem">Success!</strong> {{ message }}
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            </div>
          {% endif %}

          {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, message in messages %}
              <div class="alert alert-{{category}} alert-dismissible fade show">
                  <strong style="margin-right: 2rem">Attention! </strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
              </div>
            {% endfor %}
          {% endwith %}
          {% block content %}{% endblock %}
        <div class="spacer-80"></div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script src="../static/js/main.js"></script>
</body>
</html>

webapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="spacer-80"></div>
    <div class="content-section">
        <form method="POST" action="/login">
            {{ form.csrf_token }}
{#            {{ form.hidden_tag() }}#}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember_user(class="form-check-input") }}
                    {{ form.remember_user.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info btn-dark-blue") }}
            </div>
{#            <small class="text-muted ml-2">#}
{#                <a href="#">Forgot Password?</a>#}
{#            </small>#}
            <div class="border-top pt-3">
              <small class="text-muted float-right">
                  Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
              </small>
            </div>
            <div class="spacer-50"></div>
        </form>
    </div>
{% endblock content %}

webapp/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="spacer-30"></div>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info btn-dark-blue") }}
            </div>
          <div class="border-top pt-3">
            <small class="text-muted float-right">
                Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
            </small>
          </div>
          <div class="spacer-50"></div>
        </form>
    </div>
{% endblock content %}